name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit Changes
        run: |
          curl https://iptv-org.github.io/iptv/languages/kan.m3u > list.m3u
          curl https://iptv-org.github.io/iptv/countries/au.m3u | grep -iv -E 'melbourne|brisbane|hobart|darwin|adelaide|perth' >> list.m3u
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add list.m3u
          git diff-index --quiet HEAD || git commit -m "[Bot] Update the list"
          git pull
          git push
